INSERT INTO motores_carrera (nombre, fabricante, tipo, cilindrada_cc, potencia_hp, torque_nm, combustible, imagen_motor)
SELECT 'Motor Carrera ' || i, 'Fabricante ' || i, CASE WHEN i % 2 = 0 THEN 'V8' ELSE 'V6' END, 1600 + i * 100, 500 + i * 20, 600 + i * 15, 'Gasolina', decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8hH//Z', 'base64') FROM generate_series(1, 10) AS serie(i);

INSERT INTO especificaciones_motor (codigo_especificacion, arquitectura, numero_cilindros, aspiracion, rpm_maxima, sistema_refrigeracion, relacion_compresion, imagen_especificacion)
SELECT 'ESP' || LPAD(i::text, 3, '0'), CASE WHEN i % 2 = 0 THEN 'V' ELSE 'En linea' END, CASE WHEN i % 2 = 0 THEN 8 ELSE 6 END, CASE WHEN i % 2 = 0 THEN 'Turbo' ELSE 'Aspirado' END, 8000 + i * 100, 'Liquida', 10 + i / 10.0, decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8hH//Z', 'base64') FROM generate_series(1, 10) AS serie(i);

INSERT INTO carros_carrera (nombre, marca, modelo, categoria, peso_kg, velocidad_maxima_kmh, anio_fabricacion, imagen_carro, motor_id)
SELECT 'Carro Carrera ' || i, CASE WHEN i % 2 = 0 THEN 'Ferrari' ELSE 'Toyota' END, 'Modelo ' || i, 'Competicion', 700 + i * 5, 300 + i * 4, 2015 + i % 10, decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8hH//Z', 'base64'), i FROM generate_series(1, 10) AS serie(i);

INSERT INTO configuraciones_carro (nombre_configuracion, tipo_traccion, transmision, numero_marchas, tipo_neumatico, carga_aerodinamica, altura_mm, imagen_configuracion, especificacion_motor_id)
SELECT 'Configuracion ' || i, CASE WHEN i % 2 = 0 THEN 'Trasera' ELSE 'Integral' END, 'Secuencial', 6, 'Slick', CASE WHEN i % 2 = 0 THEN 'Alta' ELSE 'Media' END, 50 + i, decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/AP/EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8hH//Z', 'base64'), i FROM generate_series(1, 10) AS serie(i);
